// NO 'use client' — runs only on the server
import PptxGenJS from 'pptxgenjs';
import { PPTData } from '@/types';

// --------------------------
// Layout mapping (type-safe)
// --------------------------
const VALID_LAYOUT_KEYS = new Set(['title', 'content', 'section', 'twocolumn']);

const LAYOUT_MAP = {
  title: 'LAYOUT_TITLE',
  content: 'LAYOUT_CONTENT',
  section: 'LAYOUT_SECTION',
  twocolumn: 'LAYOUT_CONTENT', // Fall back to content for two-column
} as const;

type LayoutKey = keyof typeof LAYOUT_MAP;

// --------------------------
// Helper function to normalize layout
// --------------------------
function normalizeLayout(rawLayout: string | undefined): LayoutKey {
  const normalized = (rawLayout ?? 'content').toLowerCase().trim();
  
  if (VALID_LAYOUT_KEYS.has(normalized)) {
    return normalized as LayoutKey;
  }
  
  console.warn(`[PPT Generator] Unknown layout "${rawLayout}". Using "content" as fallback.`);
  return 'content';
}

// --------------------------
// Main generation function
// --------------------------
export const generatePresentationAsBase64 = async (pptData: PPTData): Promise<string> => {
  if (!pptData?.slides?.length) {
    throw new Error('Invalid PPT data: "slides" array is required and must not be empty.');
  }

  const pres = new PptxGenJS();
  pres.layout = 'LAYOUT_16x9';
  pres.author = 'AI PowerPoint Generator';
  pres.company = 'Generated by AI';
  pres.subject = 'AI Presentation';
  pres.title = pptData.title ?? 'AI Generated Presentation';

  for (let i = 0; i < pptData.slides.length; i++) {
    const slideData = pptData.slides[i];
    
    // Normalize the layout to ensure it's always valid
    const layoutKey = normalizeLayout(slideData.layout);
    
    // Don't use masterName - just add a blank slide
    // PptxGenJS doesn't require master slides for basic presentations
    const slide = pres.addSlide();

    try {
      switch (layoutKey) {
        case 'title':
          slide.addText(slideData.title ?? 'Untitled', {
            x: 0.5,
            y: 2.5,
            w: 9,
            h: 1.5,
            fontSize: 44,
            bold: true,
            color: '363636',
            align: 'center',
            valign: 'middle',
          });
          if (slideData.subtitle) {
            slide.addText(slideData.subtitle, {
              x: 0.5,
              y: 4.2,
              w: 9,
              h: 1,
              fontSize: 24,
              color: '666666',
              align: 'center',
            });
          }
          break;

        case 'section':
          slide.addText(slideData.title ?? 'Section', {
            x: 0.5,
            y: 2.5,
            w: 9,
            h: 1.5,
            fontSize: 36,
            bold: true,
            color: '0088CC',
            align: 'center',
            valign: 'middle',
          });
          break;

        case 'twocolumn':
          slide.addText(slideData.title ?? 'Two Column Slide', {
            x: 0.5,
            y: 0.5,
            w: 9,
            h: 0.8,
            fontSize: 28,
            bold: true,
            color: '363636',
          });

          const mid = Math.ceil(slideData.content.length / 2);
          const left = slideData.content.slice(0, mid);
          const right = slideData.content.slice(mid);

          if (left.length > 0) {
            slide.addText(left.map(t => ({ text: t })), {
              x: 0.5,
              y: 1.5,
              w: 4.25,
              h: 4,
              bullet: true,
              fontSize: 16,
              color: '363636',
            });
          }

          if (right.length > 0) {
            slide.addText(right.map(t => ({ text: t })), {
              x: 5.25,
              y: 1.5,
              w: 4.25,
              h: 4,
              bullet: true,
              fontSize: 16,
              color: '363636',
            });
          }
          break;

        case 'content':
        default:
          slide.addText(slideData.title ?? 'Slide Title', {
            x: 0.5,
            y: 0.5,
            w: 9,
            h: 0.8,
            fontSize: 28,
            bold: true,
            color: '363636',
          });

          if (slideData.content.length > 0) {
            slide.addText(slideData.content.map(t => ({ text: t })), {
              x: 0.5,
              y: 1.5,
              w: 9,
              h: 4,
              bullet: true,
              fontSize: 18,
              color: '363636',
            });
          }
          break;
      }
    } catch (err) {
      console.error(`[PPT Generator] Error processing slide ${i + 1}:`, err);
      // Add a fallback error slide
      slide.addText(`Error creating slide ${i + 1}`, {
        x: 1,
        y: 2,
        w: 8,
        fontSize: 24,
        color: 'FF0000',
        align: 'center',
      });
    }
  }

  const result = await pres.write({ outputType: 'base64' });
  if (typeof result !== 'string') {
    throw new Error('Failed to generate base64 string');
  }
  return result;
};